services:
  - type: web
    name: invoice-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: invoice-db
          property: connectionString

databases:
  - name: invoice-db
    databaseName: invoice_app
    user: invoice_user 