services:
  - type: web
    name: invoice-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://invoice_user:47dLkMdbpVtq2CF2XUSrisT4TXddFIm7@dpg-d0d6843uibrs73bq7fl0-a/invoice_db_jjj5

databases:
  - name: invoice-db
    databaseName: invoice_app
    user: invoice_user 